apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cn
  labels:
    k8s-app: cn
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: tcp
      path: /actuator/prometheus
      scheme: 'http'
  namespaceSelector:
    matchNames:
      - cn202003                #目标服务的namespaces
  selector:
    matchLabels:
      app: cn               #目标服务的labels