apiVersion: v1
kind: Service
metadata:
  name: cn
  labels:
    app: cn
  namespace: cn202003
spec:
  ports:
  - name: tcp
    protocol: TCP
    port: 8088
    targetPort: 8088
  selector:
    app: cn
  type: NodePort
