apiVersion: v1
kind: Service
metadata:
  name: cloud-service
  labels:
    app: cloud-service
  namespace: cn202003
spec:
  ports:
  - name: tcp
    protocol: TCP
    port: 8088
    targetPort: 8088
  selector:
    app: cloud-service
  type: NodePort
