apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cn
  labels:
    prometheus: kube-prometheus
    k8s-app: cn
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: cloud
      scheme: http
  jobLabel:  cloudnative202003
  namespaceSelector:
    matchNames:
      - cn202003                #目标服务的namespaces
  selector:
    matchLabels:
      k8s-app: cn               #目标服务的labels