apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cn
  labels:
    k8s-app: cn
    release: cloudnative
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: cloud
      path: /actuator/prometheus
      scheme: https
  jobLabel:  cloudnative202003
  namespaceSelector:
    matchNames:
      - cn202003                #目标服务的namespaces
  selector:
    matchLabels:
      k8s-app: cn               #目标服务的labels