apiVersion: v1
kind: Service
metadata:
  labels:
    app: cn
  name: cn
  namespace: cn202003
spec:
  ports:
  - name: cloud
    protocol: TCP
    port: 8088
    targetPort: 8088
    nodePort: 30478
  selector:
    app: cn
  type: NodePort
