apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-service
  name: cloud-service
  namespace: cn202003
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-service
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8088"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: cloud-service
    spec:
      containers:
      - image: harbor.edu.cn/cn202003/cloud-service:{VERSION} #lastest
        imagePullPolicy: IfNotPresent
        name: cloud-service
        ports:
        - name: tcp
          containerPort: 8088
      restartPolicy: Always
      imagePullSecrets:
      - name: mytoken
